modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
layout_mode = "Workspace"
scratchpad = []
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

# Take a screenshot
[[keybind]]
command = "Execute"
value = "scrot 'Pictures/Screenshot_%Y%m%d_%H%M%S.png'"
modifier = []
key = "Print"

# Take a screenshot and copy it to clipboard
[[keybind]]
command = "Execute"
value = "scrot '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f'"
modifier = ["Control"]
key = "Print"

# Take a screenshot of the current window
[[keybind]]
command = "Execute"
value = "scrot 'Pictures/Screenshot_%Y%m%d_%H%M%S.png' -u"
modifier = ["altkey"]
key = "Print"

# Take a screenshot of the current window and copy it to clipboard
[[keybind]]
command = "Execute"
value = "scrot '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f' -u"
modifier = ["Control", "altkey"]
key = "Print"

# Take a screenshot of the selected region
[[keybind]]
command = "Execute"
value = "scrot 'Pictures/Screenshot_%Y%m%d_%H%M%S.png' -s"
modifier = ["Shift"]
key = "Print"

# Take a screenshot of the selected region and copy it to clipboard
[[keybind]]
command = "Execute"
value = "scrot '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f' -s -f"
modifier = ["Control", "Shift"]
key = "Print"

[[keybind]]
command = "Execute"
value = "light -A 5"
modifier = []
key = "XF86XK_MonBrightnessUp"

[[keybind]]
command = "Execute"
value = "light -U 5"
modifier = []
key = "XF86XK_MonBrightnessDown"

[[keybind]]
command = "Execute"
value = "amixer -q set Capture toggle"
modifier = [""]
key = "XF86XK_AudioMicMute"

[[keybind]]
command = "Execute"
value = "amixer -q set Master toggle"
modifier = [""]
key = "XF86XK_AudioMute"

[[keybind]]
command = "Execute"
value = "amixer -q set Master 4%-"
modifier = [""]
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "amixer -q set Master 4%+"
modifier = [""]
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "ToggleSticky"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "xscreensaver-command -lock"
modifier = ["Alt", "Control"]
key = "l"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "None"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "ampersand"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "quotedbl"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "parenleft"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "egrave"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "underscore"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "ccedilla"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "ampersand"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "eacute"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "quotedbl"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "apostrophe"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "parenleft"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "minus"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "underscore"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "ccedilla"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "x"
